name: Auto Preprocessing

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn matplotlib seaborn kagglehub

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Muhamad\ Erwin\ Hariadinata.py

      - name: Commit and push updated dataset
        env:
          GIT_USER_NAME: ${{ secrets.USERNAME }}
          GIT_USER_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config user.name "${GIT_USERNAME}"
          git config user.email "${GIT_EMAIL}"

          git add preprocessing/*

          git commit -m "Auto update preprocessing results [skip ci]" || echo "No changes to commit"

          git pull --rebase origin main || echo "Rebase failed or nothing to update"

          git push || echo "No new commits to push"
