name: Auto Preprocessing

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn matplotlib seaborn kagglehub

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Muhamad\ Erwin\ Hariadinata.py

      - name: Commit and push updated dataset
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}

          git add preprocessing/final_weather_data.csv

          git commit -m "Auto update: final_weather_data.csv [skip ci]" || echo "No changes to commit"

          git push
